! pe0 - BGP AS 65000
!
frr defaults traditional
service integrated-vtysh-config
!
! Log everything (incl. debugs) to a file inside the container.
log file /etc/frr/frr.log debugging
log timestamp precision 6
!
! Debugging enabled for the base lab.
debug zebra events
debug zebra kernel
debug zebra rib detailed
debug zebra nht
debug bgp neighbor-events
debug bgp updates in
debug bgp updates out
debug bgp zebra
!
vrf vrf1
 vni 100
exit-vrf
!
vrf vrf2
 vni 200
exit-vrf
!
router bgp 65000
 no bgp ebgp-requires-policy
 bgp router-id 192.0.2.0
 neighbor tope interface remote-as external
 !
 address-family ipv4 unicast
  neighbor tope activate
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor tope activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor tope activate
  advertise-all-vni
  advertise-svi-ip
 exit-address-family
!
router bgp 65000 vrf vrf1
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family ipv6 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  advertise ipv6 unicast
 exit-address-family
exit
!
router bgp 65000 vrf vrf2
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family ipv6 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  advertise ipv6 unicast
 exit-address-family
exit
!
line vty
!
